### PR TITLE
fix(changelog): preserve custom intro and main header

### LINKED ISSUE #75: Changelog pre-existing header/intro
As discussed in https://github.com/bruits/sampo/discussions/74 , Sampo should preserve any Changelog pre-existing header/intro. 

## Describe the problem

The `update_changelog` function in `release.rs` currently:
1. Strips the package header (`# package-name`) if present
2. Recreates it with a hardcoded format
3. Loses any custom content between the header and the first version entry (`## x.y.z`)

This means badges, descriptions, notes, or any custom text before the first version is overwritten on each update. For example : 
```markdown
# Custom Changelog Header

[![npm version](https://badge.fury.io/js/package.svg)](...)
[![Build Status](https://travis-ci.org/user/package.svg)](...)

All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/).

## 1.0.0
[...]
```

Become :

```markdown
# Package Name

## 1.0.1
[...]

## 1.0.0
[...]
```

## What's the expected result?

Preserve everything before the first `## ` (h2 heading) and insert new version sections right before it. This approach preserves custom headers and intro content without requiring markdown parsing of previous entries. This won't support custom sections between the intro and version entries (e.g., an `## Unreleased` section), because this would require parsing the changelog file... I don't really like that, as I want to keep Sampo easy to opt in and out, without assuming that previous sections were generated by Sampo, and to allow users to manually edit previous release sections after generation.

### PR DESCRIPTION
**Pull request by goulvenclech**
Fix #75 . When updating changelogs, Sampo now preserves any intro content or custom main header before the first `##` section. You can also manually edit previously released entries, and Sampo will keep them intact.

As said in the issue, this won't support custom sections between the intro and version entries (e.g., an `## Unreleased` section), because this would require parsing the changelog file... I don't really like that, as I want to keep Sampo easy to opt in and out, without assuming that previous sections were generated by Sampo, and to allow users to manually edit previous release sections after generation.

## What does this change?

- `crates/sampo-core/src/release.rs`: Now split changelog with`split_intro_and_versions`, insert the freshly generated release block between them without rewriting everything.

## How is it tested?

- `crates/sampo-core/src/release.rs`: Added regression tests to cover « changelog with custom main header/intro » and « empty changelog » cases.

## How is it documented?

Updated Sampo README's changelog section.

### CODE REVIEW

File: crates/sampo-core/src/release.rs [hunk 1]
```diff
@@ -1331,6 +1331,25 @@ fn update_dependency_table_line(line: &str, new_version: &str) -> String {
...
+fn split_intro_and_versions(body: &str) -> (&str, &str) {
+    let mut offset = 0;
+    let len = body.len();
+    while offset < len {
+        if body[offset..].starts_with("## ") {
+            return body.split_at(offset);
+        }
+
+        match body[offset..].find('\n') {
+            Some(rel) => {
```
Comment (Princesseuh) [inline crates/sampo-core/src/release.rs:1343]: rel?

**Review by Princesseuh — APPROVED** [review]
